
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';

export const SHUFFLE_AUTHORS = 'SHUFFLE_AUTHORS';

export const FILTER_TOGGLE_ONE = 'FILTER_TOGGLE_ONE';
export const FILTER_SELECT_ALL = 'FILTER_SELECT_ALL';
export const FILTER_SELECT_NONE = 'FILTER_SELECT_NONE';